### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by yuki-koyama** [tedchao/PosterChild#1]
Great project! I was really impressed by the high-quality results in the paper. Thanks for sharing the code.

I am wondering if you have any plan to add some OSS license to this repository? Or, is it better to assume all rights are reserved? Thanks.

**Comment by tedchao** [comment]
Hi Yuki,

Thanks for your interest! Yes, we are planning on adding BSD/MIT or Apache license to this project/repo.
Will keep you updated!
Thanks.

--Ted

**Comment by yuki-koyama** [comment]
Great to hear that, thanks!

**Comment by tedchao** [comment]
Hi Yuki,

Our repo has been licensed. Enjoy!
Thanks.

Best,
--Ted

**Comment by yuki-koyama** [comment]
Thank you very much!
